// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi83IVf5WyCtuX6zgCyCKRDgefvRTNikw',
    appId: '1:569739288280:web:2f6c24abf6745051cc01ad',
    messagingSenderId: '569739288280',
    projectId: 'koutan-2454f',
    authDomain: 'koutan-2454f.firebaseapp.com',
    storageBucket: 'koutan-2454f.appspot.com',
    measurementId: 'G-S3HFP188ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQlhntuOY90oMp-YdauLLMZ1AF9R352dQ',
    appId: '1:569739288280:android:a93a544e252f11c2cc01ad',
    messagingSenderId: '569739288280',
    projectId: 'koutan-2454f',
    storageBucket: 'koutan-2454f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyeAXy26hQAnvYW9fHrDz9qmwhDEvXew0',
    appId: '1:569739288280:ios:c20d4d0f767af637cc01ad',
    messagingSenderId: '569739288280',
    projectId: 'koutan-2454f',
    storageBucket: 'koutan-2454f.appspot.com',
    iosBundleId: 'com.example.koutan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyeAXy26hQAnvYW9fHrDz9qmwhDEvXew0',
    appId: '1:569739288280:ios:984bdba234492dbdcc01ad',
    messagingSenderId: '569739288280',
    projectId: 'koutan-2454f',
    storageBucket: 'koutan-2454f.appspot.com',
    iosBundleId: 'com.example.koutan.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi83IVf5WyCtuX6zgCyCKRDgefvRTNikw',
    appId: '1:569739288280:web:52d3fd2d70be0ee5cc01ad',
    messagingSenderId: '569739288280',
    projectId: 'koutan-2454f',
    authDomain: 'koutan-2454f.firebaseapp.com',
    storageBucket: 'koutan-2454f.appspot.com',
    measurementId: 'G-RC278Y1Q9M',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDi83IVf5WyCtuX6zgCyCKRDgefvRTNikw',
    appId: '1:569739288280:web:3a0e512b67760c7ccc01ad',
    messagingSenderId: '569739288280',
    projectId: 'koutan-2454f',
    authDomain: 'koutan-2454f.firebaseapp.com',
    storageBucket: 'koutan-2454f.appspot.com',
    measurementId: 'G-1B6G8V5X6W',
  );
}
